### ISSUE TITLE
.env file not excluded from git repo

### ISSUE THREAD

**Issue by skluthe** [arcnaver/cs313-final#1]
Hey, you may not want to include your username and password for your postgres server in your git repo.

**Comment by skluthe** [comment]
https://github.com/arcnaver/cs313-final/blob/master/.env

**Comment by arcnaver** [comment]
Thank you for pointing that out. I've done something wrong in my .gitignore. It wasn't supposed to have been included.

**Comment by skluthe** [comment]
Anytime ;) good luck with your final!
